---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    author: ram
spec:
  replicas: 2
  template:
    metadata:
      name: httpd-pod
      labels:
        name: ram
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
...


