---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    type: mydb
    author: avd
spec:
  containers:
    - name: avdpostdb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: test123
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: testuser
...


