---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: mynginx
    author: Ram
spec:
  replicas: 2
  selector:
    matchLabels:
      name: mynginx
  template:
    metadata:
      name: mynginx-pod
      labels:
        name: mynginx
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-Service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
...

