---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-nginx
  labels:
    app: app-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /index1.html
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
...
              
