---
apiVersion: v1
kind: Pod
metadata: 
  name: tomcat-pod
  labels:
    type: webserver
    author: ram
spec:
  containers:
    - name: mytomcat
      image: tomee
      ports:
        - containerPort: 8080
          hostPort: 9090
...
