---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
 affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
         - matchExpressions:
             - key: slave1
               operator: In
               values:
                 - ram
 containers:
   - name: mynginx
     image: nginx
...
