---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-controller
  labels:
    author: ram
spec:
  replicas: 2
  template:
    metadata:
      name: tomcat-pod
      labels:
        author: ram
    spec:
      containers:
        - name: mytomcat
          image: tomcat
          ports:
            - containerPort: 8080
              hostPort: 9090
...
