---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    type: mydb
    author: avd
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    author: avd
    type: mydb
...
