---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
        - name: myphp
          image: ramkhadke/avd1
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1500m"
            requests:
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  ports:
    - port: 80
  selector:
    run: php-apache
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webserver-gke-ing
spec:
  rules:
    - host: apache.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: php-apache
                port:
                  number: 80
...
