---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    type: mysql
spec:
  containers:
    - name: mysql
      image: mysql
      volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql 
  volumes:
    - name: mysql-volume
      emptyDir: {}
...


