---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
  labels:
    name: postgres-app
    author: Ram
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-app
    spec:
      containers:
        - name: my-postgres-app
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: test123
            - name: POSTGRES_USER
              value: testuser
            - name: POSTGRES_DB
              value: mydb
...
                 
    

