---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    type: apache-appserver
spec:
  replicas: 2
  selector:
    matchLabels:
      name: apache-appserver
  template:
    metadata:
      name: apache-pod
      labels:
        name: apache-appserver
    spec:
      containers:
        - name: myapache
          image: apache
          ports:
            - containerPort: 80
...
