---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webserver-gke-ing
spec:
  rules:
    - host: tomcat.avd.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tomcat-service
                port:
                  number: 80
    - host: apache.avd.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache-service
                port:
                  number: 80
    - host: nginx.avd.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
...




